# Generated by Django 6.0 on 2025-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipientrequest',
            old_name='medical_description',
            new_name='medical_condition',
        ),
        migrations.RenameField(
            model_name='recipientrequest',
            old_name='estimated_treatment_cost',
            new_name='treatment_cost',
        ),
        migrations.RemoveField(
            model_name='recipientrequest',
            name='admin_approved_amount',
        ),
        migrations.RemoveField(
            model_name='recipientrequest',
            name='ai_recommended_amount',
        ),
        migrations.RemoveField(
            model_name='recipientrequest',
            name='illness_severity',
        ),
        migrations.RemoveField(
            model_name='recipientrequest',
            name='income_level',
        ),
        migrations.RemoveField(
            model_name='recipientrequest',
            name='project',
        ),
        migrations.RemoveField(
            model_name='recipientrequest',
            name='urgency',
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='financial_condition',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='full_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='hospital_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='medical_document',
            field=models.FileField(blank=True, null=True, upload_to='medical_docs/'),
        ),
        migrations.AlterField(
            model_name='recipientrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
