# Generated by Django 6.0 on 2025-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_medical_description_recipientrequest_medical_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientrequest',
            name='ai_explanation',
            field=models.TextField(blank=True, help_text='Explanation of AI allocation decision', null=True),
        ),
        migrations.AddField(
            model_name='recipientrequest',
            name='ai_recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='AI-recommended allocation amount', max_digits=12, null=True),
        ),
    ]
